const Product = require("../models/Product");

// --- Danh sách Category & Brand ID ĐÃ LỌC CHO SẢN PHẨM CÔNG NGHỆ ---
const CATEGORY_SMARTPHONE = "65a7e24602e12c44f599442c"; // Điện thoại thông minh
const CATEGORY_LAPTOP = "65a7e24602e12c44f599442d";    // Máy tính xách tay
const CATEGORY_WATCH = "65a7e24602e12c44f5994438";      // Đồng hồ thông minh
const CATEGORY_LIGHTING = "65a7e24602e12c44f599443f";   // Thiết bị chiếu sáng

const BRAND_APPLE = "65a7e20102e12c44f59943da";
const BRAND_SAMSUNG = "65a7e20102e12c44f59943db";
const BRAND_OPPO = "65a7e20102e12c44f59943dc";
const BRAND_HUAWEI = "65a7e20102e12c44f59943dd";
const BRAND_HP = "65a7e20102e12c44f59943e0";
const BRAND_MICROSOFT = "65a7e20102e12c44f59943de";
const BRAND_NAVIFORCE = "65a7e20102e12c44f599440b";
const BRAND_SKMEI = "65a7e20102e12c44f599440c";
const BRAND_LED_LIGHTS = "65a7e20102e12c44f59943f2";
const BRAND_CAR_AUX = "65a7e20102e12c44f599441b";
const BRAND_W1209 = "65a7e20102e12c44f599441c";
const BRAND_NEON_LIGHT = "65a7e20102e12c44f599441e";

const products = [
  {
    _id: "65a7e45902e12c44f599444e",
    title: "IPhone 15 Pro Max",
    description: "Chiếc điện thoại hàng đầu của Apple với chip A17 Bionic và camera 48MP.",
    price: 32990000,
    discountPercentage: 5.00,
    stockQuantity: 55,
    brand: BRAND_APPLE,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1F7R4skqrB3jQRnZwTmsxddsuY10hIqw2/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1AC7gmPbPtwKRaw_nrIbkyi_ZGkjZtPSO/view?usp=drive_link",
      "https://drive.google.com/file/d/1T_912e9-C9WIxh9XXCl0JBXu3yMSIltS/view?usp=drive_link",
      "https://drive.google.com/file/d/1T_912e9-C9WIxh9XXCl0JBXu3yMSIltS/view?usp=drive_link",
      "https://drive.google.com/file/d/1r4NAiXywZfpaeYD6_RxRYFPHBk618L8a/view?usp=drive_link",
      "https://drive.google.com/file/d/1F7R4skqrB3jQRnZwTmsxddsuY10hIqw2/view?usp=drive_link"
    ],
    viewCount: 3500,
    saleCount: 750,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599444f",
    title: "Samsung Galaxy S24 Ultra",
    description: "Siêu phẩm Android với bút S Pen tích hợp và khả năng zoom quang 10x.",
    price: 31990000,
    discountPercentage: 8.5,
    stockQuantity: 42,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1m4AGGf2z03IRuN1sOLYIcuAERou0p4yZ/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1cgTA9zaOnxrHOh_caTk89srqvcyqDT9K/view?usp=drive_link",
      "https://drive.google.com/file/d/1ObkcMwWwvSqgQqgfzSVzpvGysNp8Msjc/view?usp=drive_link",
      "https://drive.google.com/file/d/1t_gzKszfnAGe8CLhJDVBqDgFCMCFzpTc/view?usp=drive_link",
      "https://drive.google.com/file/d/1IQp2nKEskzJjN6jtd_3IpItipHDCAOa-/view?usp=sharing",
      "https://drive.google.com/file/d/1m4AGGf2z03IRuN1sOLYIcuAERou0p4yZ/view?usp=drive_link",
    ],
    viewCount: 2800,
    saleCount: 610,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994450",
    title: "OPPO Find X6 Pro",
    description: "Điện thoại tập trung vào camera với hệ thống xử lý hình ảnh MariSilicon X.",
    price: 18990000,
    discountPercentage: 10.0,
    stockQuantity: 65,
    brand: BRAND_OPPO,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/12inQHbBtvdwnpwLI-4Y4jH1yoCsLxrcs/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1pKk0vWbJtiBTyhWL9UXGMHh7TfJhxH2C/view?usp=drive_link",
      "https://drive.google.com/file/d/1BXEy9YET4_QfcfmRIHSU302pn1X9GYFU/view?usp=drive_link",
      "https://drive.google.com/file/d/1U5ca_JvgrG5yeieEU5dx_3s8Au8qaX22/view?usp=drive_link",
      "https://drive.google.com/file/d/1UFj_HEGDSBG1FPCX-eWu5e3yYrIIiF9b/view?usp=drive_link",
      "https://drive.google.com/file/d/12inQHbBtvdwnpwLI-4Y4jH1yoCsLxrcs/view?usp=drive_link"
    ],
    viewCount: 1900,
    saleCount: 320,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994451",
    title: "Huawei P60 Art",
    description: "Thiết kế độc đáo, camera XMAGE mạnh mẽ, chạy hệ điều hành HarmonyOS.",
    price: 24990000,
    discountPercentage: 7.25,
    stockQuantity: 30,
    brand: BRAND_HUAWEI,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1InWBprHRrziZPVQksXQyMxBcJapD-rui/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1XRMwUt1TtLVeDSL00zBnaZxxDVKx24B6/view?usp=drive_link",
      "https://drive.google.com/file/d/1Nam_pAa-tEPE5n3xy7X_M38LnNB8R9ku/view?usp=drive_link",
      "https://drive.google.com/file/d/1Mffw3Bz-MEZSmYw39XtVPjI9oU_lFaQI/view?usp=drive_link",
      "https://drive.google.com/file/d/13lv-BX-5tYDu3b8Kx6wpg9WIgtFlLtKM/view?usp=drive_link",
      "https://drive.google.com/file/d/1InWBprHRrziZPVQksXQyMxBcJapD-rui/view?usp=drive_link"
    ],
    viewCount: 1500,
    saleCount: 280,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994452",
    title: "IPhone SE (2024)",
    description: "Sức mạnh mới trong thiết kế cổ điển, hỗ trợ 5G.",
    price: 10990000,
    discountPercentage: 15.00,
    stockQuantity: 120,
    brand: BRAND_APPLE,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1dd_AyR8RC5WA5AsiGJukJAPQibLXeZI_/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1W2puMc8yxcV1AfUgyNV0j8_ac-TLFO6D/view?usp=drive_link",
      "https://drive.google.com/file/d/11Oy95yIIIMTPsecbQyd2g_lFdNorc1Ol/view?usp=drive_link",
      "https://drive.google.com/file/d/157AbeKT4T1u7OAA975n7hkIXZ_0ajifN/view?usp=drive_link",
      "https://drive.google.com/file/d/1z4gIRHeuw8osv3qIjWKcDrOLu33ZEOqC/view?usp=drive_link",
      "https://drive.google.com/file/d/1dd_AyR8RC5WA5AsiGJukJAPQibLXeZI_/view?usp=drive_link"
    ],
    viewCount: 4100,
    saleCount: 950,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994453",
    title: "Samsung Galaxy A54 5G",
    description: "Điện thoại tầm trung đáng tiền với màn hình Super AMOLED 120Hz.",
    price: 7990000,
    discountPercentage: 12.00,
    stockQuantity: 90,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1Q1T3_YlxetAcXY6iaSdY520XquwAOXBO/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1zLlQC5fk61D9_DPQ9Tc6fkcRhmdjBVe0/view?usp=drive_link",
      "https://drive.google.com/file/d/1oW0GRjx0CmpxEqonn_vZI_tAkeqm5YrS/view?usp=drive_link",
      "https://drive.google.com/file/d/1TIX4uWuVI9V97XmKpwsZ-5-GByUT4Viv/view?usp=drive_link",
      "https://drive.google.com/file/d/1JCPa1UJgZo1Sv-v1kH9oQBxKfZRywgfp/view?usp=drive_link",
      "https://drive.google.com/file/d/1Q1T3_YlxetAcXY6iaSdY520XquwAOXBO/view?usp=drive_link"
    ],
    viewCount: 3200,
    saleCount: 880,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994454",
    title: "OPPO Reno10 Z 5G",
    description: "Chuyên gia chân dung với thiết kế mỏng nhẹ và sạc nhanh SuperVOOC.",
    price: 6990000,
    discountPercentage: 11.50,
    stockQuantity: 78,
    brand: BRAND_OPPO,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1WeO9REav4bX_Zw0kUVadn5Xe-YpHfnq9/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1pKvwjn9C4tpOhLS1RklwtGsYXkLQSI5Q/view?usp=drive_link",
      "https://drive.google.com/file/d/1VDVMFdo_yUk194GhScNq3vPsbb22o_Np/view?usp=drive_link",
      "https://drive.google.com/file/d/1Tu9Z84Ec7yG6yDODilClvp5zzxwDcWk6/view?usp=drive_link",
      "https://drive.google.com/file/d/1UGkOPqmRlUMhoO4hfA0Yf_TxCaESl7K1/view?usp=drive_link",
      "https://drive.google.com/file/d/1WeO9REav4bX_Zw0kUVadn5Xe-YpHfnq9/view?usp=drive_link",
    ],
    viewCount: 1450,
    saleCount: 450,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994455",
    title: "Huawei Nova 11 Pro",
    description: "Selfie kép ấn tượng, thiết kế da thời thượng.",
    price: 14990000,
    discountPercentage: 9.99,
    stockQuantity: 50,
    brand: BRAND_HUAWEI,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1uZL3qTTEJt_vuK4fxt27gRy9oDV_aLDt/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1SVjXWrFZMXZH5wk3cP2LXkj1Kb8jXlPK/view?usp=drive_link",
      "https://drive.google.com/file/d/1d7HAUnzLuPmwI4Ccp0toT2fv0UnzZ0QT/view?usp=drive_link",
      "https://drive.google.com/file/d/16q2mN_Dl1ejqsrgL_ThVG1Zv-SC0Q5f6/view?usp=drive_link",
      "https://drive.google.com/file/d/1BZn9RITw2acFcTXuXm9Le5GUygahd6bb/view?usp=drive_link",
      "https://drive.google.com/file/d/1uZL3qTTEJt_vuK4fxt27gRy9oDV_aLDt/view?usp=drive_link",
    ],
    viewCount: 980,
    saleCount: 210,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994456",
    title: "iPhone 13 Pro (Refurbished)",
    description: "Màn hình ProMotion 120Hz và chip A15 mạnh mẽ với giá đã qua sử dụng.",
    price: 19990000,
    discountPercentage: 20.00,
    stockQuantity: 35,
    brand: BRAND_APPLE,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/11e5NvA_tSdnaYzV89aUw7bM2xxmuotTc/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1T3FAwwqwfnUmFxZqx0vFaMztk4rgt5M8/view?usp=drive_link",
      "https://drive.google.com/file/d/16_9RhZD2lrpClcMLcFRmD3Z-DCema8XW/view?usp=drive_link",
      "https://drive.google.com/file/d/1LJZsFDh5ID2FS79sfyjiVdN1hnZhrrKS/view?usp=drive_link",
      "https://drive.google.com/file/d/1EHNYDRJsuMMDgMgQanAndN9qyUH0Eb8c/view?usp=drive_link",
      "https://drive.google.com/file/d/11e5NvA_tSdnaYzV89aUw7bM2xxmuotTc/view?usp=drive_link"
    ],
    viewCount: 1700,
    saleCount: 400,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994457",
    title: "Samsung Galaxy Z Fold 5",
    description: "Điện thoại gập cao cấp, trải nghiệm màn hình lớn như máy tính bảng.",
    price: 36990000,
    discountPercentage: 6.00,
    stockQuantity: 25,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1FCjymX58886-_REyX0YFIvwHA-8OkdKt/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1dCFGBaLgZ073NoxXFDiKArE_hv3HY4_r/view?usp=drive_link",
      "https://drive.google.com/file/d/1Dbr8Wv77H3ZcqYJDvtk4qcbQpRhzuf68/view?usp=drive_link",
      "https://drive.google.com/file/d/1X-am-VPgag7WPNPF_s34gUUM7IVAaB4M/view?usp=drive_link",
      "https://drive.google.com/file/d/1vxKLcA1JpAst6MbuJ_FsKOeYOFe3LCJD/view?usp=drive_link",
      "https://drive.google.com/file/d/1FCjymX58886-_REyX0YFIvwHA-8OkdKt/view?usp=drive_link",
    ],
    viewCount: 1100,
    saleCount: 150,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994458",
    title: "OPPO A98 5G",
    description: "Pin 5000mAh bền bỉ và camera siêu sắc nét.",
    price: 5990000,
    discountPercentage: 13.50,
    stockQuantity: 110,
    brand: BRAND_OPPO,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1eQkHsK1nnN-6t2moeP1U_5-MIs9JvNzs/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1DPMqYWny7gzZuQ2kS_lsvizj3RZfqoNQ/view?usp=drive_link",
      "https://drive.google.com/file/d/1ADJAJCvXwFX2GpZVqs32uDE6YqRMuZ6b/view?usp=drive_link",
      "https://drive.google.com/file/d/1AxeSjzSJsuMXF0H5UglPWZFA_j1bMsYG/view?usp=drive_link",
      "https://drive.google.com/file/d/1VLsOoSuCJ9LvJyil7p7fjy_Bbdx_s1Wi/view?usp=drive_link",
      "https://drive.google.com/file/d/1eQkHsK1nnN-6t2moeP1U_5-MIs9JvNzs/view?usp=drive_link",
    ],
    viewCount: 1300,
    saleCount: 500,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994459",
    title: "Huawei Mate X3 (Gập)",
    description: "Điện thoại gập siêu nhẹ, chống nước IPX8.",
    price: 45000000,
    discountPercentage: 5.50,
    stockQuantity: 15,
    brand: BRAND_HUAWEI,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/18M5FyS3DVqWikXimlU3mL9Ifx21xpLfG/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1xYURkLSwndaz-k29mZ9xwShE8zYUZkiy/view?usp=drive_link",
      "https://drive.google.com/file/d/15C-Ip9HfYr-nsPlslLxu95aGW17s3bZv/view?usp=drive_link",
      "https://drive.google.com/file/d/1Kt_S3AYgSjX0onE9GdxmxIw-2eDvjCWz/view?usp=drive_link",
      "https://drive.google.com/file/d/1e3vDsgzF-zh_Dv3c-q2eql-HC16bQWf3/view?usp=drive_link",
      "https://drive.google.com/file/d/18M5FyS3DVqWikXimlU3mL9Ifx21xpLfG/view?usp=drive_link",
    ],
    viewCount: 750,
    saleCount: 80,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445a",
    title: "iPhone 14 Plus",
    description: "Màn hình lớn và thời lượng pin xuất sắc.",
    price: 22990000,
    discountPercentage: 10.00,
    stockQuantity: 70,
    brand: BRAND_APPLE,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1UHuhoZ1kMW9ZYYIwOf7Ivhy13LhLed6K/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/17DUwzLxy7Teh-UVLes7tlJDqhp82E4qQ/view?usp=drive_link",
      "https://drive.google.com/file/d/1X1WisSub9Heok-FhyQO4VDoFhsG4jjhh/view?usp=drive_link",
      "https://drive.google.com/file/d/1q6s1U_fTBRuLPzlLE22StLI2Tr8Pq0Dh/view?usp=drive_link",
      "https://drive.google.com/file/d/1Cd28BFLOo-ueP6ORLYFyifBUywvNH2nb/view?usp=drive_link",
      "https://drive.google.com/file/d/1UHuhoZ1kMW9ZYYIwOf7Ivhy13LhLed6K/view?usp=drive_link",
    ],
    viewCount: 2200,
    saleCount: 550,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445b",
    title: "Samsung Galaxy Z Flip 5",
    description: "Điện thoại gập vỏ sò thời trang với màn hình phụ lớn.",
    price: 19990000,
    discountPercentage: 7.50,
    stockQuantity: 48,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1Q1T3_YlxetAcXY6iaSdY520XquwAOXBO/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1jvVf3W41AF2E86EWoq-tBGkwIHGmYdNW/view?usp=drive_link",
      "https://drive.google.com/file/d/1_KU5q7eJ07GUcWsMFzk6pZ7YnmRt9lBt/view?usp=drive_link",
      "https://drive.google.com/file/d/1gCvNrOXVkE83BJcPd07TfTTmA9_omrrg/view?usp=drive_link",
      "https://drive.google.com/file/d/1TkA8V4BRRKjKZV0DPAqr-VNFiUKwqPjq/view?usp=drive_link",
      "https://drive.google.com/file/d/1Pk-qxKmFLgjQu5cqLlNLxBf6Wjy7QXy0/view?usp=drive_link",
    ],
    viewCount: 1600,
    saleCount: 390,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445c",
    title: "OPPO K10 Pro 5G",
    description: "Hiệu năng mạnh mẽ với chip Snapdragon.",
    price: 9990000,
    discountPercentage: 14.00,
    stockQuantity: 62,
    brand: BRAND_OPPO,
    category: CATEGORY_SMARTPHONE,
    thumbnail: "https://drive.google.com/file/d/1PfMgz7D5FKmRWqsPHvpEa8swbPtzXb-S/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1WJaWQ5u7ZBY3Ja06RtWxDOKEIdc2RMBK/view?usp=drive_link",
      "https://drive.google.com/file/d/1PsExFElyZbnswweODCQmYnjv67dQhm6T/view?usp=drive_link",
      "https://drive.google.com/file/d/10wA3y-0Ei_NcNGQFYe2z9WrX2cq7FMIs/view?usp=drive_link",
      "https://drive.google.com/file/d/1wB0JoCjuhKwJjtps8_LECWyKwjmE3_5D/view?usp=drive_link",
      "https://drive.google.com/file/d/1PfMgz7D5FKmRWqsPHvpEa8swbPtzXb-S/view?usp=drive_link",
    ],
    viewCount: 1050,
    saleCount: 270,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445d",
    title: "MacBook Pro 16 M3 Max",
    description: "Hiệu năng không đối thủ cho các chuyên gia sáng tạo.",
    price: 72990000,
    discountPercentage: 4.00,
    stockQuantity: 25,
    brand: BRAND_APPLE,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1RGVoNNyIqBJgbY4bt1dg4a1U3-UH5dyT/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1qPPoiWPi8F47bO5xp2qSsZZi8gw6SRzS/view?usp=drive_link",
      "https://drive.google.com/file/d/1eCjDh2kBgtytG2OWuclSj7wgmx8YbGyx/view?usp=drive_link",
      "https://drive.google.com/file/d/1TDZ2F-5qPPdSub5I8tYPhFrfly6b_g_u/view?usp=drive_link",
      "https://drive.google.com/file/d/1a8gJ0GbpKY2Wepoxza-a3Z4XFW6FX1tc/view?usp=drive_link",
      "https://drive.google.com/file/d/1RGVoNNyIqBJgbY4bt1dg4a1U3-UH5dyT/view?usp=drive_link",
    ],
    viewCount: 1800,
    saleCount: 210,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445e",
    title: "Samsung Galaxy Book4 Ultra",
    description: "Màn hình Dynamic AMOLED 2X, thiết kế mỏng nhẹ.",
    price: 49990000,
    discountPercentage: 6.50,
    stockQuantity: 30,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1PaXJzka5gtAyrWxg7-3NPuE33Xus2Ljv/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/19_58HZs6kjTiqOa7BZhXp2oqqSaAJCaz/view?usp=drive_link",
      "https://drive.google.com/file/d/1LCJVqf8ahupPbIEqXCJhM6k2A73UiZoq/view?usp=drive_link",
      "https://drive.google.com/file/d/1PX1QCyvgPNce9grwNttE9gVYkn-VdnA0/view?usp=drive_link",
      "https://drive.google.com/file/d/1NIDjTsfj_vk4L9ksRCZocKvLyBp52KTL/view?usp=drive_link",
      "https://drive.google.com/file/d/1PaXJzka5gtAyrWxg7-3NPuE33Xus2Ljv/view?usp=drive_link",
    ],
    viewCount: 1400,
    saleCount: 180,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599445f",
    title: "Microsoft Surface Laptop Studio 2",
    description: "Máy trạm di động với màn hình cảm ứng xoay lật sáng tạo.",
    price: 55990000,
    discountPercentage: 5.00,
    stockQuantity: 20,
    brand: BRAND_MICROSOFT,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1H2oC465SSu7bL96F1yNCBcy0XlvbYk87/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1A7fxitfyXAfn-JHUbsJv7HiSA_FslBEf/view?usp=drive_link",
      "https://drive.google.com/file/d/1BA0SScYlZa5ubPZdfSFWA-R4XmVaNzx8/view?usp=drive_link",
      "https://drive.google.com/file/d/1ujTmR4kwNiBDzvF5PkMWw6UZUl4WCzmd/view?usp=drive_link",
      "https://drive.google.com/file/d/1Fx75Vl2-2kHZyticIy-6cg8OAFGrmyMA/view?usp=drive_link",
      "https://drive.google.com/file/d/1H2oC465SSu7bL96F1yNCBcy0XlvbYk87/view?usp=drive_link",
    ],
    viewCount: 950,
    saleCount: 110,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994460",
    title: "Huawei MateBook X Pro (2024)",
    description: "Màn hình FullView và thiết kế kim loại nguyên khối sang trọng.",
    price: 39990000,
    discountPercentage: 7.00,
    stockQuantity: 38,
    brand: BRAND_HUAWEI,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/128JNcKNGiw5Y0SMOXNZMnIWOst9mGvri/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1zAPS9C84cgJaMArm1VMKdcGSTLP6iWu7/view?usp=drive_link",
      "https://drive.google.com/file/d/1sUYCIEJp-ZH-TSB9fk8MPngxkr1XGLR4/view?usp=drive_link",
      "https://drive.google.com/file/d/1Fy89X7-FBScAaEv1W_GfsLtztPBx-FWU/view?usp=drive_link",
      "https://drive.google.com/file/d/15A3d_WQYLpzqVgWm0AnSQYLKZdu8_heB/view?usp=drive_link",
      "https://drive.google.com/file/d/128JNcKNGiw5Y0SMOXNZMnIWOst9mGvri/view?usp=drive_link",
    ],
    viewCount: 1200,
    saleCount: 160,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994461",
    title: "MacBook Air 13 M2",
    description: "Siêu mỏng, siêu nhẹ, hiệu năng tuyệt vời cho công việc văn phòng.",
    price: 24990000,
    discountPercentage: 8.00,
    stockQuantity: 60,
    brand: BRAND_APPLE,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1cUj84zFeiur2Tm3_roqVYl43oqbEJZn2/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/16WUa6qrZ4_zY_f948QTfDn18ax2Vv_NG/view?usp=drive_link",
      "https://drive.google.com/file/d/1trbdtn3knI2BUD0i-W-VO8aHiUwBdwRc/view?usp=drive_link",
      "https://drive.google.com/file/d/14CDWRPOJ4IKdKwUKIJe8oa5QoQVOryk9/view?usp=drive_link",
      "https://drive.google.com/file/d/11mx2jMUOBVIPHOTm39iQ6gWwTyrmNwkK/view?usp=drive_link",
      "https://drive.google.com/file/d/1cUj84zFeiur2Tm3_roqVYl43oqbEJZn2/view?usp=drive_link",
    ],
    viewCount: 2500,
    saleCount: 450,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994462",
    title: "Samsung Galaxy Book3 Pro",
    description: "Laptop cao cấp, mỏng nhẹ với màn hình 120Hz.",
    price: 31990000,
    discountPercentage: 11.00,
    stockQuantity: 45,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1n4_udiHVTgioSOtvbQC6RNmVZ-XDfOLH/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1_bqc-5Z7MecfSSy27U7Ii8G7Ipg5i1MQ/view?usp=drive_link",
      "https://drive.google.com/file/d/1IBP50C7iGXqz215UZyqpn7H9rJyuN_Mg/view?usp=drive_link",
      "https://drive.google.com/file/d/1IgOnqta-uls2akME4hLSrRTmYExP8BO4/view?usp=drive_link",
      "https://drive.google.com/file/d/1byByv03YfZPJJu2SRjBeYJBDj9xL2sv2/view?usp=drive_link",
      "https://drive.google.com/file/d/1n4_udiHVTgioSOtvbQC6RNmVZ-XDfOLH/view?usp=drive_link",
    ],
    viewCount: 1550,
    saleCount: 250,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994463",
    title: "HP Pavilion Gaming 15",
    description: "Laptop gaming tầm trung với card đồ họa NVIDIA.",
    price: 14990000,
    discountPercentage: 15.00,
    stockQuantity: 70,
    brand: BRAND_HP,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1CA7DshQ-s1r5Cz9-LpU3GF7QYQfnbTCE/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1kMuLH4MbWs257K0zZc0zgm-dtJdjv1mF/view?usp=drive_link",
      "https://drive.google.com/file/d/1976mYLaINlOeicsQfFR3JGdgxYMsYLm9/view?usp=drive_link",
      "https://drive.google.com/file/d/17v7YVeSPq6ta22c_i9zvvUBM_7_i10R_/view?usp=drive_link",
      "https://drive.google.com/file/d/12sIUyjhI_tptAVc6UdUOYJ6YM7BxCdv8/view?usp=drive_link",
      "https://drive.google.com/file/d/1CA7DshQ-s1r5Cz9-LpU3GF7QYQfnbTCE/view?usp=drive_link",
    ],
    viewCount: 3000,
    saleCount: 520,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994464",
    title: "Microsoft Surface Pro 9",
    description: "Máy tính bảng kiêm laptop 2 trong 1, chạy Windows.",
    price: 27990000,
    discountPercentage: 9.50,
    stockQuantity: 50,
    brand: BRAND_MICROSOFT,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1OnW4vIFfIHzxOELKwq9vChIqwMHCYOIy/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1vN3olMp6ys829-GRswyTl17bQisGEnrj/view?usp=drive_link",
      "https://drive.google.com/file/d/1NEot518WEkXMTskA-DjHUTLa55eHp_2i/view?usp=drive_link",
      "https://drive.google.com/file/d/1G_040Ycjzzq6fMRmgsDCxveu4JAtvnBB/view?usp=drive_link",
      "https://drive.google.com/file/d/1N2h3OBRyYKsPKXYJfpM3A3Op_9D9bbpG/view?usp=drive_link",
      "https://drive.google.com/file/d/1OnW4vIFfIHzxOELKwq9vChIqwMHCYOIy/view?usp=drive_link",
    ],
    viewCount: 1650,
    saleCount: 280,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994465",
    title: "Huawei MateBook D 16 (2024)",
    description: "Màn hình lớn 16 inch, phù hợp cho học tập và làm việc.",
    price: 15490000,
    discountPercentage: 12.50,
    stockQuantity: 85,
    brand: BRAND_HUAWEI,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1eL0BFlni5vo2h0BX1AgVm_i48Vd54qTU/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1LEazWqSXiamCOuFkJIYKjCY2RrIqvpwF/view?usp=drive_link",
      "https://drive.google.com/file/d/1eDWxXSelJAVtciLMvqG9GkMUMCe1oTgW/view?usp=drive_link",
      "https://drive.google.com/file/d/1yMN8PWM1UDlrPxdom1OpWuekisda_Jqt/view?usp=drive_link",
      "https://drive.google.com/file/d/15TddS12f05xQnALF1hy_DsaHk9zWmhzq/view?usp=drive_link",
      "https://drive.google.com/file/d/1eL0BFlni5vo2h0BX1AgVm_i48Vd54qTU/view?usp=drive_link",
    ],
    viewCount: 2050,
    saleCount: 390,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994466",
    title: "MacBook Pro 14 M3",
    description: "Sự cân bằng giữa hiệu năng và tính di động.",
    price: 45990000,
    discountPercentage: 5.50,
    stockQuantity: 35,
    brand: BRAND_APPLE,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1HlgtkiHcaJnAX9CbgDynWhoho3F6pCRs/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1qPPoiWPi8F47bO5xp2qSsZZi8gw6SRzS/view?usp=drive_link",
      "https://drive.google.com/file/d/1eCjDh2kBgtytG2OWuclSj7wgmx8YbGyx/view?usp=drive_link",
      "https://drive.google.com/file/d/1TDZ2F-5qPPdSub5I8tYPhFrfly6b_g_u/view?usp=drive_link",
      "https://drive.google.com/file/d/1a8gJ0GbpKY2Wepoxza-a3Z4XFW6FX1tc/view?usp=drive_link",
      "https://drive.google.com/file/d/1HlgtkiHcaJnAX9CbgDynWhoho3F6pCRs/view?usp=drive_link",
    ],
    viewCount: 1300,
    saleCount: 150,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994467",
    title: "Samsung Galaxy Book2 360",
    description: "Laptop xoay gập 360 độ linh hoạt.",
    price: 25990000,
    discountPercentage: 14.00,
    stockQuantity: 40,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1cclfzpso_9RltOxJVfCiUwOmMWGRA8ip/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1if-0MwB-eZI6yBwB6JKwdmXZumXYGf50/view?usp=drive_link",
      "https://drive.google.com/file/d/1MUBpL5dS-ERzcelJxmECRppXos7lKJ2Y/view?usp=drive_link",
      "https://drive.google.com/file/d/1bK920iOz6xxZYNLZYcV_2IgJKj_iq0Nn/view?usp=drive_link",
      "https://drive.google.com/file/d/1O7YCrnNl8t47AUTBQjEromL50pvZoCLv/view?usp=drive_link",
      "https://drive.google.com/file/d/1cclfzpso_9RltOxJVfCiUwOmMWGRA8ip/view?usp=drive_link",
    ],
    viewCount: 1150,
    saleCount: 200,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994468",
    title: "HP Envy x360 13",
    description: "Thiết kế cao cấp, màn hình OLED sắc nét, 2 trong 1.",
    price: 22990000,
    discountPercentage: 10.50,
    stockQuantity: 48,
    brand: BRAND_HP,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1ZK8M1WFYMeufP_zxGS8nGUMj5MwLu_vw/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/130k0M7JagSXngLJRHBfZAaZVdmqLV6J2/view?usp=drive_link",
      "https://drive.google.com/file/d/13lxqIjns_If6xCY0k3WHNg7dIghl7ZMu/view?usp=drive_link",
      "https://drive.google.com/file/d/1mIDNmpoN6av2ZujUXU2OwnCrPRseugDo/view?usp=drive_link",
      "https://drive.google.com/file/d/193Tbzui-IJBqdRSt7c2IG0qC02aofpv9/view?usp=drive_link",
      "https://drive.google.com/file/d/1ZK8M1WFYMeufP_zxGS8nGUMj5MwLu_vw/view?usp=drive_link",
    ],
    viewCount: 1750,
    saleCount: 300,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994469",
    title: "3D Embellishment Art Lamp",
    description:
      "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    price: 20,
    discountPercentage: 16.49,
    stockQuantity: 54,
    brand: "65a7e20102e12c44f59943f2",
    category: "65a7e24602e12c44f5994431",
    thumbnail: "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/28/1.jpg",
      "https://cdn.dummyjson.com/product-images/28/2.jpg",
      "https://cdn.dummyjson.com/product-images/28/3.png",
      "https://cdn.dummyjson.com/product-images/28/4.jpg",
      "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
    ],
    viewCount: 1103,
    saleCount: 105,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446a",
    title: "Microsoft Surface Go 4",
    description: "Máy tính bảng/Laptop nhỏ gọn, cơ động.",
    price: 13990000,
    discountPercentage: 18.00,
    stockQuantity: 95,
    brand: BRAND_MICROSOFT,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/1Pvjchpl79SlUpde1YqWqpGztJJbeOIzf/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1FOKqY_vJeM1fXfENLf0DajwVZnBlsk-3/view?usp=drive_link",
      "https://drive.google.com/file/d/1PUOWio9sD7RPXfilO1y709wGMsjW6FXw/view?usp=drive_link",
      "https://drive.google.com/file/d/10ajqKNIQQh6CYltHh7PbgmscwEOZQZgW/view?usp=drive_link",
      "https://drive.google.com/file/d/1tR7PvVmny5rYLGcz9mEbStGC5OxJfy4V/view?usp=drive_link",
      "https://drive.google.com/file/d/1Pvjchpl79SlUpde1YqWqpGztJJbeOIzf/view?usp=drive_link",
    ],
    viewCount: 2300,
    saleCount: 600,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446b",
    title: "Huawei MateBook 14s",
    description: "Laptop hiệu năng cao, màn hình 3:2 tỷ lệ vàng.",
    price: 29990000,
    discountPercentage: 8.50,
    stockQuantity: 32,
    brand: BRAND_HUAWEI,
    category: CATEGORY_LAPTOP,
    thumbnail: "https://drive.google.com/file/d/10tzIwykgCWz7x5wNA9G5Z6lE66tEiLtw/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1UUtMGP4oUWsH9Y2Yv9DXzpv72TVmHChS/view?usp=drive_link",
      "https://drive.google.com/file/d/1Ou1nV_67Wp1ZDURzzi5wXW1zim3koBFh/view?usp=drive_link",
      "https://drive.google.com/file/d/1rjc012zdbuEnMzjXE_bmVZJqLS2snmSU/view?usp=drive_link",
      "https://drive.google.com/file/d/1TqfWPv-dhq4LddTde7Ei04ikLEgYVg-A/view?usp=drive_link",
      "https://drive.google.com/file/d/10tzIwykgCWz7x5wNA9G5Z6lE66tEiLtw/view?usp=drive_link",
    ],
    viewCount: 880,
    saleCount: 130,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446c",
    title: "Apple Watch Series 9 GPS + Cellular",
    description: "Đồng hồ thông minh theo dõi sức khỏe và có thể gọi điện độc lập.",
    price: 12990000,
    discountPercentage: 7.00,
    stockQuantity: 80,
    brand: BRAND_APPLE,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1VrW4sG8VUfM9RA0ab3cnAFeAYrBRFbF1/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/18XseLrNdlYI3-VyKgqHv-w1Ka56BpmqR/view?usp=drive_link",
      "https://drive.google.com/file/d/15AssDhnZ8i66gbnit1ffVv7cLRss33lB/view?usp=drive_link",
      "https://drive.google.com/file/d/1UVZ1tHu_QXsZRuoNInlndK80X7UKrfH6/view?usp=drive_link",
      "https://drive.google.com/file/d/1YhSneTmAtyN9o16D1orhJ3-JD-6QWedy/view?usp=drive_link",
      "https://drive.google.com/file/d/1VrW4sG8VUfM9RA0ab3cnAFeAYrBRFbF1/view?usp=drive_link",
    ],
    viewCount: 4500,
    saleCount: 950,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446d",
    title: "Samsung Galaxy Watch 6 Classic",
    description: "Thiết kế cổ điển với vòng bezel xoay vật lý, phân tích giấc ngủ nâng cao.",
    price: 8490000,
    discountPercentage: 10.00,
    stockQuantity: 75,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/16vKpL6VBJV0SElQEpeQy2t9FND7pms4W/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1_e0FQhCd6ZFfRt9egbwBCjeVyMYdMTdD/view?usp=drive_link",
      "https://drive.google.com/file/d/1LXwZS7PazJclKO3Th6ywC9tPMhDX5gou/view?usp=drive_link",
      "https://drive.google.com/file/d/1Wb5BMyEVaPs5kNJQc8LNtzIYKr1RX8fB/view?usp=drive_link",
      "https://drive.google.com/file/d/1PySy5QR-YXj3hcs2njgizxd-eDTkQdPD/view?usp=drive_link",
      "https://drive.google.com/file/d/16vKpL6VBJV0SElQEpeQy2t9FND7pms4W/view?usp=drive_link",
    ],
    viewCount: 3800,
    saleCount: 880,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446e",
    title: "Huawei Watch GT 4 Pro",
    description: "Thời lượng pin siêu dài, theo dõi hoạt động thể thao chuyên sâu.",
    price: 6990000,
    discountPercentage: 12.00,
    stockQuantity: 90,
    brand: BRAND_HUAWEI,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1wmLBln5ENL282Yh2aZO--Ks4YakLJTqM/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/191UwY4uonwRddsdEUEOIxUhvqDhOJ0ZQ/view?usp=drive_link",
      "https://drive.google.com/file/d/1ieeliICEdeWFhMBlF76QDAJOWfI7fM-u/view?usp=drive_link",
      "https://drive.google.com/file/d/1ImwlFUlU1LnwuWoAiOtwyiEeGgfNq_Ug/view?usp=drive_link",
      "https://drive.google.com/file/d/1WogAyqRv3Yf6i1IDDoIvaDn7gVBW8CwI/view?usp=drive_link",
      "https://drive.google.com/file/d/1wmLBln5ENL282Yh2aZO--Ks4YakLJTqM/view?usp=drive_link",
    ],
    viewCount: 2100,
    saleCount: 450,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599446f",
    title: "Naviforce S-Series Sport Watch",
    description: "Đồng hồ điện tử thể thao, chống nước 5ATM.",
    price: 890000,
    discountPercentage: 25.00,
    stockQuantity: 150,
    brand: BRAND_NAVIFORCE,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1MYB6mCMknclOeBps92OcmWgzIyB3e_GR/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1xLqI25FZzmmZtPILQXdNKdXIcDe1p7B3/view?usp=drive_link",
      "https://drive.google.com/file/d/1KgCYwjMfJdWGHvHzXAM5bV5NZ83xJK9_/view?usp=drive_link",
      "https://drive.google.com/file/d/1Fgf-xdkGhB4Cy7snUqfsc3oMPc6KsoJO/view?usp=drive_link",
      "https://drive.google.com/file/d/1dt24ufJNUvQZAcTk10JjswyXv8Y8G_KN/view?usp=drive_link",
      "https://drive.google.com/file/d/1MYB6mCMknclOeBps92OcmWgzIyB3e_GR/view?usp=drive_link",
    ],
    viewCount: 1800,
    saleCount: 600,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994470",
    title: "SKMEI Digital LED Watch",
    description: "Đồng hồ kỹ thuật số cơ bản với đèn LED.",
    price: 390000,
    discountPercentage: 30.00,
    stockQuantity: 200,
    brand: BRAND_SKMEI,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1C6t9JFc0_FZp5tWFbgz-LV_mjUVWg__-/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1oRgnBvr1-_lEh_ReTKsLsW-UhfyCYuoR/view?usp=drive_link",
      "https://drive.google.com/file/d/1gXFNgeMZ8gdekPkF4Bx7w1qeEegWDkkX/view?usp=drive_link",
      "https://drive.google.com/file/d/1pEpufdkbPGc6mQa2HpP4zqiUNsd-HAup/view?usp=drive_link",
      "https://drive.google.com/file/d/1vnF1VcCL_VGd2qTblfQ9gWYBgXipy4ur/view?usp=drive_link",
      "https://drive.google.com/file/d/1C6t9JFc0_FZp5tWFbgz-LV_mjUVWg__-/view?usp=drive_link",
    ],
    viewCount: 2200,
    saleCount: 750,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994471",
    title: "Apple Watch SE (Gen 2)",
    description: "Đồng hồ thông minh giá phải chăng, các tính năng cơ bản của Apple.",
    price: 6490000,
    discountPercentage: 15.00,
    stockQuantity: 100,
    brand: BRAND_APPLE,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1qyCHo4Ijou_hoJfeRNtdDdPDAYZ-kdK9/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1aWKvx8RVGsg6ENrU5YPDQE6TYN6SAsyb/view?usp=drive_link",
      "https://drive.google.com/file/d/1HpPIPQ8lkhLmb1IRpiDmM2vLC_fXHfzK/view?usp=drive_link",
      "https://drive.google.com/file/d/1uCyTbd7avF1pz2V5OVXd2iPX1zgenWbx/view?usp=drive_link",
      "https://drive.google.com/file/d/1gEDf7XK-qnpXNogjUod8Oygp7UOp3tKr/view?usp=drive_link",
      "https://drive.google.com/file/d/1qyCHo4Ijou_hoJfeRNtdDdPDAYZ-kdK9/view?usp=drive_link",
    ],
    viewCount: 2800,
    saleCount: 700,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994472",
    title: "Samsung Galaxy Fit3",
    description: "Vòng đeo tay thông minh theo dõi hoạt động và nhịp tim.",
    price: 1290000,
    discountPercentage: 18.00,
    stockQuantity: 120,
    brand: BRAND_SAMSUNG,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1Xd9GTTAGn5X1JsVLS32rjRYmv4SUjF-H/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1ov-aFCuxibj2P1h5j9SxR_hUAxHkW7E2/view?usp=drive_link",
      "https://drive.google.com/file/d/13JfhxeGJq4AkIkaMRFAj_WTYVQK_ycFh/view?usp=drive_link",
      "https://drive.google.com/file/d/105cjsPxUW1SfLAPLN-nYfD63lBhOZqEE/view?usp=drive_link",
      "https://drive.google.com/file/d/1nwKWxzUC5NSBfqlcMKVEUQ2si47tE-RE/view?usp=drive_link",
      "https://drive.google.com/file/d/1Xd9GTTAGn5X1JsVLS32rjRYmv4SUjF-H/view?usp=drive_link",
    ],
    viewCount: 1500,
    saleCount: 480,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994473",
    title: "Huawei Band 8",
    description: "Vòng đeo tay thể dục siêu mỏng, theo dõi SpO2.",
    price: 890_000,
    discountPercentage: 20.00,
    stockQuantity: 140,
    brand: BRAND_HUAWEI,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1NMrMJp5gg0UjeprMLNe2NVtxXQd2EGQt/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/16voSjU5f6JW0jcS5va5EJ8PEJORZVL_p/view?usp=drive_link",
      "https://drive.google.com/file/d/1DWavU1izdpNgJjRLP54W3xvH-uP8So-0/view?usp=drive_link",
      "https://drive.google.com/file/d/1f_n6YRNAaKJ6ekBTcyqNhk5rw1oy0ZSr/view?usp=drive_link",
      "https://drive.google.com/file/d/1k9UwijjdyzUDxK1q-iVjlCOXMlsJVYQ6/view?usp=drive_link",
      "https://drive.google.com/file/d/1NMrMJp5gg0UjeprMLNe2NVtxXQd2EGQt/view?usp=drive_link",
    ],
    viewCount: 1600,
    saleCount: 520,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994474",
    title: "Naviforce Men's Chronograph",
    description: "Đồng hồ thạch anh kết hợp tính năng chronograph.",
    price: 1190000,
    discountPercentage: 15.50,
    stockQuantity: 88,
    brand: BRAND_NAVIFORCE,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1NizeJbwkrFvbiS2x1aX2DpnFxxgG7sKt/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1uHcX8TvzTINIl6IMwIBOC6pn9hxq7r-t/view?usp=drive_link",
      "https://drive.google.com/file/d/1nZgWv459Ib4vGvPT6_xDAkN4rdeCHe__/view?usp=drive_link",
      "https://drive.google.com/file/d/15NtSImQMtEHVtBMDoQdZMw_gXC0nbFQp/view?usp=drive_link",
      "https://drive.google.com/file/d/1NwPm1KtGnYH_2HamTMTzSWvtsRJOdA_Y/view?usp=drive_link",
      "https://drive.google.com/file/d/1NizeJbwkrFvbiS2x1aX2DpnFxxgG7sKt/view?usp=drive_link",
    ],
    viewCount: 950,
    saleCount: 300,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994475",
    title: "SKMEI Smart Pedometer Watch",
    description: "Đồng hồ thông minh cơ bản theo dõi bước chân.",
    price: 550000,
    discountPercentage: 22.00,
    stockQuantity: 160,
    brand: BRAND_SKMEI,
    category: CATEGORY_WATCH,
    thumbnail: "https://drive.google.com/file/d/1CGEGDBS5wc9Z3eottxOT2SdT3-ev1Icb/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/14szA2PIkglbcnrxdZ98eXoAM1yMT9tUl/view?usp=drive_link",
      "https://drive.google.com/file/d/1_8SuFaizM7Fe0VyqopZTiJomybB2U7Qw/view?usp=drive_link",
      "https://drive.google.com/file/d/1sR-EVnWU7z9LR6-IYlxhnATohbWCXSgC/view?usp=drive_link",
      "https://drive.google.com/file/d/18oRAxhJg4G73423foD7TlePDxwUMq8Zg/view?usp=drive_link",
      "https://drive.google.com/file/d/1CGEGDBS5wc9Z3eottxOT2SdT3-ev1Icb/view?usp=drive_link",
    ],
    viewCount: 1250,
    saleCount: 450,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994476",
    title: "Bóng đèn thông minh LED RGB",
    description: "Bóng đèn LED đổi màu, điều khiển qua Wi-Fi.",
    price: 290000,
    discountPercentage: 8.00,
    stockQuantity: 300,
    brand: BRAND_LED_LIGHTS,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1Uy2Gxen72temtBVz8zkBfMRhzvI910nl/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1LbV3QO19Je8c_NNQ3vTUZx8SbPUwf7q4/view?usp=drive_link",
      "https://drive.google.com/file/d/1Thcb520upws0rEEj9JOzrYzyfQQKcgKD/view?usp=drive_link",
      "https://drive.google.com/file/d/1Bo8rVWaWdCHV5VODZGKsbLl3y4BFPt-d/view?usp=drive_link",
      "https://drive.google.com/file/d/1zfj8N--aKS_W6ZiUuoQxgo8YItR5kjwc/view?usp=drive_link",
      "https://drive.google.com/file/d/1Uy2Gxen72temtBVz8zkBfMRhzvI910nl/view?usp=drive_link",
    ],
    viewCount: 4000,
    saleCount: 1500,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994477",
    title: "Bộ điều khiển nhiệt độ DC 12V",
    description: "Module kiểm soát nhiệt độ kỹ thuật số W1209.",
    price: 120000,
    discountPercentage: 15.00,
    stockQuantity: 500,
    brand: BRAND_W1209,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1he3jLJLHuG5VUzzK2gI1Buox-W7b27ld/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1OnqF1ea2aMA4I7JK8dA5I_Joga4Brs0d/view?usp=drive_link",
      "https://drive.google.com/file/d/1brcOy2NtgMqXJ8-hNPyhMmR-vsyV2Uam/view?usp=drive_link",
      "https://drive.google.com/file/d/1Du-mNF73JE6SpOWh3dX__h1Jy0P6R7-z/view?usp=drive_link",
      "https://drive.google.com/file/d/1zmpE_N0_cpH09BzS8uRReF3KnkphWnw5/view?usp=drive_link",
      "https://drive.google.com/file/d/1he3jLJLHuG5VUzzK2gI1Buox-W7b27ld/view?usp=drive_link",
    ],
    viewCount: 5500,
    saleCount: 2500,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994478",
    title: "Dây LED Neon dẻo 5m",
    description: "Dây đèn LED Neon linh hoạt cho trang trí.",
    price: 490000,
    discountPercentage: 10.00,
    stockQuantity: 400,
    brand: BRAND_NEON_LIGHT,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1oOmyAyAlPM2fQjmavVAfbDYmPpMvQ9qD/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1mGxyLqMsOaQ3zU25pVx_xg7ofPXQTPU2/view?usp=drive_link",
      "https://drive.google.com/file/d/1T2aleQekLH7R22CaVozntXThvXM3b0Aq/view?usp=drive_link",
      "https://drive.google.com/file/d/1QgQmTeaobZ0Wh-fbVznAfrxm8zIR0p1x/view?usp=drive_link",
      "https://drive.google.com/file/d/1NJpcw0bgf4Q3yrkkT_CDeAsWw86zFH4G/view?usp=drive_link",
      "https://drive.google.com/file/d/1oOmyAyAlPM2fQjmavVAfbDYmPpMvQ9qD/view?usp=drive_link",
    ],
    viewCount: 3200,
    saleCount: 1100,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f5994479",
    title: "Adapter Car Aux sang USB-C",
    description: "Bộ chuyển đổi âm thanh Car Aux sang cổng USB Type-C.",
    price: 180000,
    discountPercentage: 20.00,
    stockQuantity: 600,
    brand: BRAND_CAR_AUX,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1AGIF14ifXUBtMoyxEVSQ86Ws7B7CVdz3/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1a941AWu5SwFrsKd7TpdYKaDtVdmiIwpv/view?usp=drive_link",
      "https://drive.google.com/file/d/1H5TYmEnFJbYijeeurLivsMkbibq-jE4n/view?usp=drive_link",
      "https://drive.google.com/file/d/10oUVnD5_SZvxwdkVs1jti8fZ1d5YlNVz/view?usp=drive_link",
      "https://drive.google.com/file/d/1j8afMei9WLFKUmXAKLkOzxnUIi2GjLm0/view?usp=drive_link",
      "https://drive.google.com/file/d/1AGIF14ifXUBtMoyxEVSQ86Ws7B7CVdz3/view?usp=drive_link",
    ],
    viewCount: 4800,
    saleCount: 1800,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447a",
    title: "Đèn bàn LED chống cận",
    description: "Đèn bàn LED điều chỉnh độ sáng, bảo vệ mắt.",
    price: 550000,
    discountPercentage: 10.00,
    stockQuantity: 150,
    brand: BRAND_LED_LIGHTS,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1v7fYc2QidXLvYeJg6gcSPRZdtKJpfhTh/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1lTLKiUnYINIVLMY-i9gI-4ZiaFfXY4sI/view?usp=drive_link",
      "https://drive.google.com/file/d/1V_wHT6yBIHGRHVxYwcAaTqeb64UF03q8/view?usp=drive_link",
      "https://drive.google.com/file/d/1gyMGIEc68zgrCsV3b6ZmeVj_w3pG7Mjq/view?usp=drive_link",
      "https://drive.google.com/file/d/1_D85Fv7gYFkOk4CRaG02hXreZDA8uiCS/view?usp=drive_link",
      "https://drive.google.com/file/d/1v7fYc2QidXLvYeJg6gcSPRZdtKJpfhTh/view?usp=drive_link",
    ],
    viewCount: 1800,
    saleCount: 750,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447b",
    title: "Cảm biến nhiệt độ và độ ẩm kỹ thuật số",
    description: "Cảm biến chính xác cho các dự án điện tử.",
    price: 220000,
    discountPercentage: 5.00,
    stockQuantity: 350,
    brand: BRAND_W1209,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1WvzqnFPmJwRTYorsGjRgPLueQtNeoj5D/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1TcWtXr8CCCSTdJhA-M-kCHs-6zdrkv-F/view?usp=drive_link",
      "https://drive.google.com/file/d/1Jog9vfRuwLRCpOuSVAAWHc1trpl98_5V/view?usp=drive_link",
      "https://drive.google.com/file/d/14TpLKTm2Fsagp7tYZy17KMxPOOa5LiPn/view?usp=drive_link",
      "https://drive.google.com/file/d/12h9pyRjJLRjfn_tNR3Ce14PJjnBj3mel/view?usp=drive_link",
      "https://drive.google.com/file/d/1WvzqnFPmJwRTYorsGjRgPLueQtNeoj5D/view?usp=drive_link",
    ],
    viewCount: 2500,
    saleCount: 880,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447c",
    title: "Đèn trang trí Neon hình mây",
    description: "Đèn trang trí phòng ngủ hình mây, chạy bằng pin/USB.",
    price: 350000,
    discountPercentage: 15.00,
    stockQuantity: 250,
    brand: BRAND_NEON_LIGHT,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/13nB6j3oUDkoatbP281QvTWRz-R_Su68k/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1W4e_8aFheWnas66BSENQRELKp6d3GFq3/view?usp=drive_link",
      "https://drive.google.com/file/d/1MnQLlakUyZnhYq-WCIRYbbEGaUf2qW7e/view?usp=drive_link",
      "https://drive.google.com/file/d/1h84cyaCL4BLu5dJkCByAxNoXKsOaMXTL/view?usp=drive_link",
      "https://drive.google.com/file/d/1pyi2LsFOiN9u9llv7uEI7QIi0rzDY0nu/view?usp=drive_link",
      "https://drive.google.com/file/d/13nB6j3oUDkoatbP281QvTWRz-R_Su68k/view?usp=drive_link",
    ],
    viewCount: 1400,
    saleCount: 650,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447d",
    title: "Cáp chuyển đổi âm thanh Aux 3.5mm",
    description: "Cáp chất lượng cao để kết nối thiết bị âm thanh.",
    price: 150000,
    discountPercentage: 25.00,
    stockQuantity: 700,
    brand: BRAND_CAR_AUX,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1Q3OzxNgPU0H7pMMQWRQCiTM1kizla2JG/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1XIDUyJ80CfCwWLgb-uCBUoCRVNSgYssf/view?usp=drive_link",
      "https://drive.google.com/file/d/1mQgvJZ10kc8FNHzzXZ7HlYe6kxpHRSnC/view?usp=drive_link",
      "https://drive.google.com/file/d/12k6sQl03ZcrQks2mW6RL1zf7k9K6HJRs/view?usp=drive_link",
      "https://drive.google.com/file/d/12D07vkSViKAOmRQL82eGo9JoCD380S6w/view?usp=drive_link",
      "https://drive.google.com/file/d/1Q3OzxNgPU0H7pMMQWRQCiTM1kizla2JG/view?usp=drive_link",
    ],
    viewCount: 6000,
    saleCount: 3000,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447e",
    title: "Đèn năng lượng mặt trời cảm biến chuyển động",
    description: "Đèn LED ngoài trời tiết kiệm điện.",
    price: 450000,
    discountPercentage: 12.00,
    stockQuantity: 200,
    brand: BRAND_LED_LIGHTS,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1vgOLy5pa-hUlHXQfoKtRppNmuevz0NNa/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1Tv8md6-Kd9G8_I1oxCdVexyPnc92pl9Y/view?usp=drive_link",
      "https://drive.google.com/file/d/1brRBlZfOysrEj2WuhzMOiNJLH-7zxgTm/view?usp=drive_link",
      "https://drive.google.com/file/d/1llnaXfM6ur-75aDf5wVZv3WJh8JMjfXc/view?usp=drive_link",
      "https://drive.google.com/file/d/19drIEuSVmgP-TwbZ_n9SUueWjnZOAeIy/view?usp=drive_link",
      "https://drive.google.com/file/d/1vgOLy5pa-hUlHXQfoKtRppNmuevz0NNa/view?usp=drive_link",
    ],
    viewCount: 2000,
    saleCount: 950,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  },
  {
    _id: "65a7e45902e12c44f599447f",
    title: "Module Relay 1 kênh 12V",
    description: "Module rơle điều khiển cho các dự án điện tử DIY.",
    price: 80000,
    discountPercentage: 35.00,
    stockQuantity: 800,
    brand: BRAND_W1209,
    category: CATEGORY_LIGHTING,
    thumbnail: "https://drive.google.com/file/d/1TGsd4OhZEuev1ROQ1aLGLzRTjVY2IutB/view?usp=drive_link",
    images: [
      "https://drive.google.com/file/d/1bANQge4R3XgWQ-U4y_jS2jAyroR69UM3/view?usp=drive_link",
      "https://drive.google.com/file/d/1jXRid9SJCFuoNpmd3R5dcFu2sD1wG_g3/view?usp=drive_link",
      "https://drive.google.com/file/d/1PMF73fypolcf5rKRButyUMqVZmUnAgJ8/view?usp=drive_link",
      "https://drive.google.com/file/d/17-D0gePyoEagdR6rPqHDfnVEGQXaMvMx/view?usp=drive_link",
      "https://drive.google.com/file/d/1TGsd4OhZEuev1ROQ1aLGLzRTjVY2IutB/view?usp=drive_link",
    ],
    viewCount: 7500,
    saleCount: 4000,
    isDeleted: false,
    updatedAt: "2024-02-07T09:22:57.840Z",
  }
];

exports.seedProduct = async () => {
  try {
    // Kiểm tra xem đã có dữ liệu chưa
    const existingProducts = await Product.countDocuments();

    if (existingProducts > 0) {
      console.log(`Đã có ${existingProducts} sản phẩm trong database. Skip seeding.`);
      return;
    }

    await Product.insertMany(products);
    console.log("Product seeded successfully");
  } catch (error) {
    console.log(error);
  }
};
